### ISSUE TITLE
/sbin/btrfs not considered when searching for btrfs command

### ISSUE THREAD

**Issue by czernitko** [nazar-pc/just-backup-btrfs#3]
Hi, thank you for this useful script!
I had to add /sbin/btrfs to the list of files being searched for, since it is a default location of btrfs command on Gentoo.
Regards,
Peter

**Comment by nazar-pc** [comment]
Fixed in a108705, thanks!

**Comment by czernitko** [comment]
Wow, that was INCREDIBLY quick! Thank you very much and have a nice weekend :)
