### ISSUE TITLE
Integration with snapper

### ISSUE THREAD

**Issue by Magissia** [nazar-pc/just-backup-btrfs#6]
o/

Would be nice to be able to integrate with snapper : 
Instead of doing a new snapshot and transfer it, transfer the snapshots made by snapper and apply destination_other rules only, ignoring local snapshot creation and cleanup.

**Comment by nazar-pc** [comment]
I think what you want to achieve is already implemented in another project I've made here: https://github.com/nazar-pc/btrfs-sync-subvolumes
I'm using it to replicate snapshots from online HDD to backup offline HDD.
