### ISSUE TITLE
Snapshot rollover not working properly

### ISSUE THREAD

**Issue by HannesJo0139** [nazar-pc/just-backup-btrfs#8]
I wanna use your script with the following config:

	[{
		"source_mounted_volume"        : "/mnt/root/btrfs-backup/@",
		"destination_within_partition" : "/mnt/root/btrfs-backup/@snapshots/root",
		"destination_other_partition"  : null,
		"date_format"                  : "Y-m-d_H:i:s",
		"keep_snapshots"               : {
			"hour"  : 3,
			"day"   : 5,
			"month" : 3,
			"year"  : 0
		}
	}]

As you can see I wanna have snaps of the last 3 hours. Unfortunately this is not what your script does. It is called via hourly cron. Today I started my PC at 10:00. First snap was created 10:17. Followed by 11:17, 12:17.
So far, so good. Creating the 13:17 snapshot I expected the 10:17 snap to be deleted (or not if it is considered as daily snap). In fact, snaps 11:17 and 12:17 got deleted. My apologies if I am wrong but that is not expected behavior, right?

**Comment by HannesJo0139** [comment]
Attached content of history.db after 13:17
![Screenshot from 2020-03-31 13-42-15](https://user-images.githubusercontent.com/42114183/78022693-ae2fbd00-7355-11ea-83e3-07b2ad11f8b1.png)


I actually dont know why it has kept two daily snaps of yesterday btw. But with the next cron at 14:17, it deleted one of them. I dont get it. See new history.db after 14:17
![Screenshot from 2020-03-31 14-31-58](https://user-images.githubusercontent.com/42114183/78026992-dd95f800-735c-11ea-80e8-7e82020da08b.png)


See history.db after 15:17
![Screenshot from 2020-03-31 15-35-00](https://user-images.githubusercontent.com/42114183/78032495-63b63c80-7365-11ea-881f-4b5c2f2e40c4.png)

**Comment by nazar-pc** [comment]
Those rules specify how many snapshots will be kept, not for how long.
Essentially whenever new snapshot is made, a flag is set upfront.
Then as time goes on, all snapshots older than 1 hour that don't have `keep_hour = 1` are deleted.

So your configuration says to keep 3 snapshots per hour, 5 snapshots per day and 3 per month.
This is why you have snapshots from yesterday.

There is no way to configure 3 hours interval separately unfortunately.

**Comment by HannesJo0139** [comment]
Hmm ok, I dont know but in your readme it says "it makes rotation of snapshots by removing old ones and keeping as many snapshots as you want.".
I think that describes it the way I wanted to use it? Delete old snaps every hour but keep the newest 3. 

I mean, it is actually not removing the old ones but some previous ones if there are more than 3. I cannot see where it is holding 3 snaps at all?

It surprises me myself that after several years I am the first to ask these questions. Somehow I don't understand the idea behind your rotation algorithm at all. So sorry for the stupid questions. The cron has now been running for 2 days and I see sometimes 4, sometimes 5 snaps. Hourly snaps sometimes three, sometimes just two. I can't see where my configuration is reflected. Which are the 3 snaps that were kept in the shown screenshots?

**Comment by nazar-pc** [comment]
It does remove old snapshots, but in a different way than you expect. You you don't want to keep snapshots beyond an hour, you need to set `0` for day, month and year.

If you run cron often, you may end up creating more snapshots, and they will be kept for up to an hour, after which the algorithm kicks in and removes everything that has zeroes in the database.

Also as snapshot creation is not always instant, timestamp of the snapshot will fluctuate a few seconds back and forth over time, so you may have a bit more snapshots at times, but it shouldn't be critical anyway.

**Comment by HannesJo0139** [comment]
Alright, got it! Thanks for your kind reply.
